# Kbuild rules for MotoMAGX kernel module "hellomoto" for testing purposes.
# Written by EXL, 27-Oct-2021.

include ${PROPFILES}

MODULE_NAME = hellomoto

CFLAGS += -DMOTOMAGX -O2 -I$(STD_INCPATH)
CFLAGS += -DAURA

obj-m := $(MODULE_NAME).o
